name: Build and deploy (using pex files)

# workflow works for both full and branch deployments
on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
  push:
    branches:
      - "main"
      - "master"
  workflow_dispatch:

env:
  DAGSTER_CLOUD_URL: ${{ secrets.DAGSTER_CLOUD_URL }}
  DAGSTER_CLOUD_API_TOKEN: ${{ secrets.DAGSTER_CLOUD_API_TOKEN }}

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    name: Pex build and deploy
    strategy:
      fail-fast: false
    env:
      # force a custom base image until we auto publish new images
      CUSTOM_BASE_IMAGE: "ghcr.io/dagster-io/dagster-cloud-serverless-base-py3.8:1.0.15-pex-execute-run"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          path: project-repo
      - name: Pex build and deploy
        # pin action to the pex-testing branch so we can iterate faster
        uses: dagster-io/dagster-cloud-action/actions/build_deploy_pex@pex-testing
        with:
          dagster_cloud_file: "$GITHUB_WORKSPACE/project-repo/dagster_cloud.yaml"
          build_output_dir: "$GITHUB_WORKSPACE/build"
          python_version: "3.8"
